# Generated by Django 5.1 on 2024-12-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_regno', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('student_dob', models.DateField(blank=True, null=True)),
                ('student_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'core_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Department_code', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('default_role', models.CharField(blank=True, max_length=200, null=True)),
                ('Password', models.CharField(max_length=100)),
                ('confirm_Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'application_user',
                'managed': False,
            },
        ),
    ]
