# Generated by Django 4.2.20 on 2025-03-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "category_table",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch", models.CharField(max_length=50)),
                ("regulations", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=50)),
                ("semester", models.IntegerField()),
                ("course_code", models.CharField(max_length=10)),
                ("course_title", models.CharField(max_length=255)),
                ("lecturer", models.IntegerField()),
                ("tutorial", models.IntegerField()),
                ("practical", models.IntegerField()),
                ("total_contact_periods", models.IntegerField()),
                ("credits", models.IntegerField()),
            ],
            options={
                "db_table": "course",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="regulation_master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regulation_year", models.IntegerField()),
                ("regulation_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "equipment_regulation_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_regno",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("student_dob", models.DateField(blank=True, null=True)),
                (
                    "student_password",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "core_student",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Student_cgpa",
            fields=[
                (
                    "reg_no",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("batch", models.CharField(max_length=100)),
                ("student_name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("cgpa", models.FloatField()),
                ("sslc", models.FloatField()),
                ("hsc", models.CharField(blank=True, max_length=20, null=True)),
                ("diploma", models.CharField(blank=True, max_length=20, null=True)),
                ("bag_of_log", models.IntegerField()),
                ("history_of_arrear", models.IntegerField()),
                (
                    "admission_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("semester1", models.CharField(blank=True, max_length=20, null=True)),
                ("semester2", models.CharField(blank=True, max_length=20, null=True)),
                ("semester3", models.CharField(blank=True, max_length=20, null=True)),
                ("semester4", models.CharField(blank=True, max_length=20, null=True)),
                ("semester5", models.CharField(blank=True, max_length=20, null=True)),
                ("semester6", models.CharField(blank=True, max_length=20, null=True)),
                ("semester7", models.CharField(blank=True, max_length=20, null=True)),
                ("semester8", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "application_student",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "subject_type_table",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("user_name", models.CharField(max_length=100)),
                ("staff_id", models.CharField(max_length=100)),
                ("Department", models.CharField(max_length=100)),
                ("Department_code", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                (
                    "default_role",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("Password", models.CharField(max_length=100)),
                ("confirm_Password", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "application_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="assignreviewers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reviewer1", models.CharField(blank=True, max_length=200, null=True)),
                ("reviewer2", models.CharField(blank=True, max_length=200, null=True)),
                ("reviewer3", models.CharField(blank=True, max_length=200, null=True)),
                ("assignedat", models.DateField(auto_now_add=True)),
                ("regulation", models.CharField(blank=True, max_length=200, null=True)),
                ("coursecode", models.CharField(blank=True, max_length=200, null=True)),
                ("coursename", models.CharField(blank=True, max_length=200, null=True)),
                ("batch", models.CharField(blank=True, max_length=200, null=True)),
                ("sem", models.IntegerField()),
                ("department", models.CharField(blank=True, max_length=200, null=True)),
                ("expname", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "desegnation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="departments",
            fields=[
                (
                    "dept_code",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("department", models.CharField(max_length=500)),
                ("department_description", models.CharField(max_length=100)),
                ("degree_code", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="faculty_master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_id", models.IntegerField()),
                (
                    "faculty_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="final_outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_no", models.CharField(blank=True, max_length=20, null=True)),
                ("batch", models.CharField(blank=True, max_length=200, null=True)),
                ("semester", models.CharField(blank=True, max_length=200, null=True)),
                ("guide_name", models.CharField(blank=True, max_length=200, null=True)),
                ("outcome", models.CharField(blank=True, max_length=200, null=True)),
                ("web_url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "journal_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("volume", models.CharField(blank=True, max_length=200, null=True)),
                ("page_no", models.CharField(blank=True, max_length=200, null=True)),
                ("doi", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "impact_factor",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "project_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("filed_date", models.DateField(blank=True, null=True)),
                ("published_date", models.DateField(blank=True, null=True)),
                (
                    "patent_web_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "outcome_certificate",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("filed_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "patent_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "patent_type",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("granted_date", models.DateField(blank=True, null=True)),
                (
                    "inventor_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="internal_review_mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("reg_no", models.IntegerField()),
                ("department", models.CharField(max_length=50)),
                ("semester", models.IntegerField()),
                ("course_code", models.CharField(max_length=10, unique=True)),
                ("review_1", models.IntegerField()),
                ("review_2", models.IntegerField()),
                ("review_3", models.IntegerField()),
                ("total", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=300)),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("reg_no", models.CharField(blank=True, max_length=20, null=True)),
                ("batch", models.CharField(max_length=300)),
                ("entry_status", models.CharField(max_length=300)),
                ("title", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
                (
                    "project_type",
                    models.CharField(
                        choices=[("internal", "Internal"), ("external", "External")],
                        max_length=50,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company_guide_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "internal_guide_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("semester", models.IntegerField(blank=True, null=True)),
                ("course_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "course_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_outcome_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Application", "Application"),
                            ("Product", "Produch"),
                            ("Research", "Research"),
                            ("Patent", "patent"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("National Conference", "National Conference"),
                            ("International Conference", "International Conference"),
                            ("Scopus", "Scopus"),
                            ("SCIE", "SCIE"),
                            ("SCI", "SCI"),
                            ("UGC", "UGC"),
                            ("Otheres", "Otheres"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "outcome_certificate",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "achieved",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "yes"), ("no", "no")],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="review_marks_master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_name", models.CharField(max_length=100)),
                ("faculty_role", models.CharField(max_length=100)),
                ("reviewer_type", models.CharField(max_length=100)),
                ("student_name", models.CharField(max_length=100)),
                ("reg_no", models.CharField(max_length=20)),
                ("batch", models.CharField(max_length=50)),
                ("review_number", models.IntegerField()),
                ("regulations", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=50)),
                ("semester", models.IntegerField()),
                ("course_code", models.CharField(max_length=10)),
                (
                    "company_guide_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "internal_guide_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("criteria_1", models.IntegerField()),
                ("criteria_2", models.IntegerField()),
                ("criteria_3", models.IntegerField()),
                ("criteria_4", models.IntegerField()),
                ("criteria_5", models.IntegerField()),
                ("criteria_6", models.IntegerField()),
                ("criteria_7", models.IntegerField()),
                ("criteria_8", models.IntegerField()),
                ("criteria_9", models.IntegerField()),
                ("criteria_10", models.IntegerField()),
                ("total", models.IntegerField()),
            ],
        ),
    ]
