# Generated by Django 3.2 on 2025-03-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsReviewMarksMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(max_length=20)),
                ('review_number', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('guide_marks', models.TextField(blank=True, null=True)),
                ('reviewer1_marks', models.TextField(blank=True, null=True)),
                ('reviewer2_marks', models.TextField(blank=True, null=True)),
                ('reviewer3_marks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects_review_marks_master',
                'managed': False,
            },
        ),
    ]
