# Generated by Django 5.1 on 2024-12-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField()),
                ('faculty_name', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
