# Generated by Django 5.0.6 on 2025-03-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectsreviewmarksmaster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsreviewmarksmaster',
            options={},
        ),
    ]
