# Generated by Django 5.1 on 2024-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_faculty_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=300)),
                ('batch', models.CharField(max_length=300)),
                ('entry_status', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_guide_name', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('internal_guide_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
