# Generated by Django 5.0.6 on 2025-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_hod_assigned_reviewer_alter_project_achieved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='review_assasment_criteria_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_number', models.IntegerField()),
                ('review_criteria', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
    ]
