# Generated by Django 5.1.6 on 2025-03-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_assignedreviewers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedReviewers',
        ),
    ]
