# Generated by Django 5.1.6 on 2025-03-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_assignreviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reg_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
