# Generated by Django 5.1.6 on 2025-03-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reg_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
