# Generated by Django 5.1.6 on 2025-03-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignreviewers',
            name='reg_no',
            field=models.CharField(max_length=50),
        ),
    ]
