# Generated by Django 5.1.6 on 2025-03-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_assignreviewers_reg_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='regulation_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation_year', models.IntegerField()),
                ('regulation_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'equipment_regulation_master',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='assignreviewers',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='assignreviewers',
            name='coursecode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignreviewers',
            name='coursename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignreviewers',
            name='regulation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
