# Generated by Django 5.1.6 on 2025-03-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_regulation_master_remove_assignreviewers_reg_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_cgpa',
            fields=[
                ('reg_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('cgpa', models.FloatField()),
                ('sslc', models.FloatField()),
                ('hsc', models.CharField(blank=True, max_length=20, null=True)),
                ('diploma', models.CharField(blank=True, max_length=20, null=True)),
                ('bag_of_log', models.IntegerField()),
                ('history_of_arrear', models.IntegerField()),
                ('admission_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('semester1', models.CharField(blank=True, max_length=20, null=True)),
                ('semester2', models.CharField(blank=True, max_length=20, null=True)),
                ('semester3', models.CharField(blank=True, max_length=20, null=True)),
                ('semester4', models.CharField(blank=True, max_length=20, null=True)),
                ('semester5', models.CharField(blank=True, max_length=20, null=True)),
                ('semester6', models.CharField(blank=True, max_length=20, null=True)),
                ('semester7', models.CharField(blank=True, max_length=20, null=True)),
                ('semester8', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'application_student',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='assignreviewers',
            name='batch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignreviewers',
            name='sem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
