# Generated by Django 5.1.6 on 2025-03-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignreviewers',
            name='review_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
