# Generated by Django 5.1.6 on 2025-03-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_category_course_subjecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignreviewers',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
