# Generated by Django 5.1.6 on 2025-03-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_assignreviewers_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignreviewers',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignreviewers',
            name='desegnation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assignreviewers',
            name='expname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
