# Generated by Django 5.1.6 on 2025-03-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_assignreviewers_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='guide_alloted_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField()),
                ('nmae', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=225)),
                ('batch', models.CharField(max_length=50)),
                ('regulations', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_title', models.CharField(max_length=255)),
                ('company_guide_name', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_guide_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
