# Generated by Django 5.1.6 on 2025-03-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_rename_nmae_guide_alloted_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='course_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='course_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
