# Generated by Django 5.1.6 on 2025-03-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_course_code_project_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='course_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
