# Generated by Django 5.1.6 on 2025-03-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_project_course_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guide_alloted_data',
        ),
    ]
