# Generated by Django 5.1.6 on 2025-03-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_delete_guide_alloted_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='internal_review_mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('reg_no', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('review_1', models.IntegerField()),
                ('review_2', models.IntegerField()),
                ('review_3', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='review_marks_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_role', models.CharField(max_length=100)),
                ('reviewer_type', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('reg_no', models.IntegerField()),
                ('batch', models.CharField(max_length=50)),
                ('review_number', models.IntegerField()),
                ('regulations', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('company_guide_name', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_guide_name', models.CharField(blank=True, max_length=255, null=True)),
                ('criteria_1', models.IntegerField()),
                ('criteria_2', models.IntegerField()),
                ('criteria_3', models.IntegerField()),
                ('criteria_4', models.IntegerField()),
                ('criteria_5', models.IntegerField()),
                ('criteria_6', models.IntegerField()),
                ('criteria_7', models.IntegerField()),
                ('criteria_8', models.IntegerField()),
                ('criteria_9', models.IntegerField()),
                ('criteria_10', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
