# Generated by Django 5.1.6 on 2025-03-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_internal_review_mark_review_marks_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('dept_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=500)),
                ('department_status', models.CharField(max_length=100)),
                ('degree_code', models.IntegerField()),
            ],
        ),
    ]
