# Generated by Django 5.1.6 on 2025-03-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='department_status',
            new_name='department_description',
        ),
        migrations.AlterField(
            model_name='review_marks_master',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
    ]
