# Generated by Django 5.1.6 on 2025-03-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_rename_department_status_departments_department_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_marks_master',
            name='reg_no',
            field=models.CharField(max_length=20),
        ),
    ]
