# Generated by Django 5.1.6 on 2025-03-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_review_marks_master_reg_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects_project',
        ),
    ]
