# Generated by Django 5.1.6 on 2025-03-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_project_options_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
