# Generated by Django 5.1.6 on 2025-03-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_project_options_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
