# Generated by Django 5.1.6 on 2025-03-18 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
    ]
