# Generated by Django 5.1.6 on 2025-03-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='achieved',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=models.CharField(blank=True, choices=[('National Conference', 'National Conference'), ('International Conference', 'International Conference'), ('Scopus', 'Scopus'), ('SCIE', 'SCIE'), ('SCI', 'SCI'), ('UGC', 'UGC'), ('Otheres', 'Otheres')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_outcome_type',
            field=models.CharField(blank=True, choices=[('Application', 'Application'), ('Product', 'Produch'), ('Research', 'Research'), ('Patent', 'patent')], max_length=50, null=True),
        ),
    ]
