# Generated by Django 5.1.6 on 2025-03-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_ooutcome_addtional'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ooutcome_addtional',
            new_name='final_outcome',
        ),
    ]
