# Generated by Django 5.1.6 on 2025-03-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_rename_ooutcome_addtional_final_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_outcome',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
