# Generated by Django 5.1.6 on 2025-03-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_final_outcome_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_outcome',
            name='filed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='final_outcome',
            name='filed_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='final_outcome',
            name='granted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='final_outcome',
            name='inventor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='final_outcome',
            name='outcome_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='final_outcome',
            name='patent_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='final_outcome',
            name='patent_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='final_outcome',
            name='patent_web_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='final_outcome',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final_outcome',
            name='batch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='final_outcome',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='final_outcome',
            name='guide_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='final_outcome',
            name='impact_factor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='final_outcome',
            name='journal_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='final_outcome',
            name='outcome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='final_outcome',
            name='page_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='final_outcome',
            name='reg_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='final_outcome',
            name='semester',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='final_outcome',
            name='volume',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='final_outcome',
            name='web_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
